### ISSUE TITLE
Documentation icon linking to commits

### ISSUE THREAD

**Issue by Jameskmonger** [kentcdodds/all-contributors#7]
The documentation icon on the three contributors in `README.md` links to commits by that user. The info in `README.md` doesn't explain this, as the field next to `Documentation` is empty.

**Comment by kentcdodds** [comment]
Thanks for pointing that out...

I'm actually not sure what to do about this. Sometimes documentation lives in the README.md, other times it lives in a separate site... I'm thinking that we'll just say that it should be linked to any relevant information indicating their contributions (whether that be their commits to the project or otherwise). Wanna make a PR (be sure to add yourself to the list of contributors :smile:)

**Comment by Jameskmonger** [comment]
I don't necessarily object to it not linking to their commits, @kentcdodds.. just think that the documentation in this project's `README.md` should explain the link (if any).

**Comment by kentcdodds** [comment]
Right, agreed.

**Comment by Jameskmonger** [comment]
I'll submit a PR in a few minutes, @kentcdodds :smile:
